export const JobCategory = [
  "Information Technology & Software Development",
  "Business & Management",
  "Sales & Marketing",
  "Finance & Accounting",
  "Human Resources",
  "Customer Service & Support",
  "Healthcare & Medical",
  "Engineering",
  "Design & Creative",
  "Education & Training",
  "Legal",
  "Logistics & Supply Chain",
  "Manufacturing & Production",
  "Retail & Hospitality",
  "Media & Communications",
  "Non-Profit & Social Services",
  "Real Estate & Property Management",
  "Science & Research",
  "Transportation & Warehousing",
  "Government & Public Administration",
];
